### ISSUE TITLE
LAN dns server

### ISSUE THREAD

**Issue by Pantyhose-X** [IngoZenz/personaldnsfilter#162]
I hope that the Android version can create a LAN dns server
LAN dns server to GoogleDNS,NextDNS
LAN dns server 192.168.1.100>DNSfilter>GoogleDNS, DNS>Internet
Advantages of LAN dns server, it can be set to filter on Router
My phone runs 24 hours

**Comment by IngoZenz** [comment]
In case your question is about if it is possible to use personalDNSfilter on Android as DNS server in your LAN, the answer is yes.

However it requires root mode and to disable the adv, option "Allow only local DNS proxy access" in order to allow acces from outside the phone.

In addition you migth need to enable "prevent device sleep" in order to keep teh phone "awake".

 
 

Gesendet: Montag, 05. Juli 2021 um 03:07 Uhr
Von: "Pantyhose-X" ***@***.***>
An: "IngoZenz/personaldnsfilter" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [IngoZenz/personaldnsfilter] LAN dns server (#162)


 

I hope that the Android version can create a LAN dns server
LAN dns server to GoogleDNS,NextDNS
LAN dns192.168.1.100>parental control >GoogleDNS,NextDNS>
My phone runs 24 hours

**Comment by Pantyhose-X** [comment]
> In case your question is about if it is possible to use personalDNSfilter on Android as DNS server in your LAN, the answer is yes. However it requires root mode and to disable the adv, option "Allow only local DNS proxy access" in order to allow acces from outside the phone. In addition you migth need to enable "prevent device sleep" in order to keep teh phone "awake".     Gesendet: Montag, 05. Juli 2021 um 03:07 Uhr Von: "Pantyhose-X" ***@***.***> An: "IngoZenz/personaldnsfilter" ***@***.***> Cc: "Subscribed" ***@***.***> Betreff: [IngoZenz/personaldnsfilter] LAN dns server (#162)   I hope that the Android version can create a LAN dns server LAN dns server to GoogleDNS,NextDNS LAN dns192.168.1.100>parental control >GoogleDNS,NextDNS> My phone runs 24 hours — You are receiving this because you are subscribed to this thread. Reply to 

Can be run in adb mode, no root required

**Comment by IngoZenz** [comment]
No idea - just try it ...
I assume it won't work...
Opening port 53 on Android is not possible without root ...

**Comment by Pantyhose-X** [comment]
> No idea - just try it ... I assume it won't work... Opening port 53 on Android is not possible without root ...

@IngoZenz Now a large number of DNS servors, do not use 53 port [DNSCrypt servers  https://dnscrypt.info/public-servers](https://dnscrypt.info/public-servers)

**Comment by Pantyhose-X** [comment]
> No idea - just try it ... I assume it won't work... Opening port 53 on Android is not possible without root ...

- Use [Shizuku](https://github.com/RikkaApps/Shizuku) alternative root
