### ISSUE TITLE
EnergizedProtection is no longer a reputable source due to its nearly dead state

### ISSUE THREAD

**Issue by lucamp** [IngoZenz/personaldnsfilter#212]
Hi,
Energized is heavily present in personalDNSfilter's preset lists; unfortunately the project is nearly dead and it's going on only with automatism, please read https://github.com/EnergizedProtection/block/issues/916

At the current state, it's not reliable to have it in the default list since average users will end up trusting it but resulting in legitimate sites broken, such as

https://github.com/EnergizedProtection/block/issues/908
https://github.com/EnergizedProtection/block/issues/893
https://github.com/EnergizedProtection/block/issues/891
https://github.com/EnergizedProtection/block/issues/889 (link is death, just try another video on the right)

Please remove Energized and replace it with other sources such as GoodbyeAds and OISD

Thanks for your app
Luca

**Comment by IngoZenz** [comment]
Thanks for letting me know. Will check this...

Regards, Ingo

 
 

Gesendet: Montag, 23. Mai 2022 um 20:00 Uhr
Von: "lucamp" ***@***.***>
An: "IngoZenz/personaldnsfilter" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [IngoZenz/personaldnsfilter] EnergizedProtection is no longer a reputable source due to its nearly dead state (Issue #212)


 

Hi,
Energized is heavily present in personalDNSfilter's preset lists; unfortunately the project is nearly dead and it's going on only with automatism, please read EnergizedProtection/block#916

At the current state, it's not reliable to have it in the default list since average users will end up trusting it but resulting in legitimate sites broken, such as

EnergizedProtection/block#908
EnergizedProtection/block#893
EnergizedProtection/block#891
EnergizedProtection/block#889 (link is death, just try another video on the right)

Please remove Energized and replace it with other sources such as GoodbyeAds and OISD

Thanks for your app
Luca

**Comment by lucamp** [comment]
> Thanks for letting me know. Will check this... Regards, Ingo

No reply at all from Energized dev in 2 months at my "dead issue 916" listed in the first message.

Issues keep going at https://github.com/EnergizedProtection/block/issues with no fix and zero response by dev. For instance, energized is blocking Instagram DM (issue #920).

Please remove Energized from personalDNSfilter lists

Sincerely
Luca

**Comment by IngoZenz** [comment]
removed with https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.53.5

**Comment by lucamp** [comment]
New hosts are available only after a configuration reset, this means that average end users will never notice the changes. Is this done on purpose?
