### ISSUE TITLE
[Feature Request]  employ the same strategy as Intra app but in rooted device

### ISSUE THREAD

**Issue by hamedsbt** [IngoZenz/personaldnsfilter#244]
Hi, thanks for the awesome idea and app.
In my country, many social media sources are blocked, such as Facebook, WhatsApp, Telegram, LinkedIn, Youtube, and so on. 
I can unblock LinkedIn and Youtube with the Intra app. (it's free opensource too)
But I can't unblock LinkedIn or YouTube using my personal DNS filter in rooted or VPN mode! I can resolve IP via personaldnsfilter too.
What is the difference between Intra and personaldnsfilter?
Because I prefer to use personaldnsfilter with root instead of Intra, can you employ the same strategy to assist people like me in unblocking?

Thank you!

**Comment by ChaosNicro** [comment]
Not the creator, but it seems like Intra works by enabling an encrypted upstream DNS server replacing the one that is likely manipulating your Queries. Have you set a custom upstream server in the DNS field? Since by default it uses the system-DNS.
Easiest way to check would be to select the pencil next to the DNS-field, enabling the checkbox for manual servers, confirming the change, then hitting restart.

**Comment by ChaosNicro** [comment]
True, it's not a traditional VPN. but Intra is marketed as a DoH tool utilizing Google and cloudflare as the upstream. Since there is no mention of encryption outside of DNS it stands to reason that pDNSf can act to replace it if an encrypted upstream is used. I'm not familiar with censoring methods, so I don't know if ISPs firewall udp 53 in places. One might need to choose specifically a DoH endpoint.

**Comment by IngoZenz** [comment]
Nothing which can be fixed by pDNSf
