### ISSUE TITLE
[BUG] Whitelisted mode currently redundant/not working

### ISSUE THREAD

**Issue by ghost** [IngoZenz/personaldnsfilter#328]
The whitelisting is actually redundant. It is never triggered and it does not override any other rules. The piece in the [AdditionalHosts.txt](https://github.com/IngoZenz/personaldnsfilter/blob/master/app/src/main/assets/additionalHosts.txt) which says:
```
# PRIORITIES in case of conflicting entries
# 1. Explicit entries without wildcards
# 2. Wildcard entries prioritized along the sequence in this file
# 3. Downloaded blocklist
```
Is incorrect. Rules 1 and 3 would mean that explicitly whitelisted entries, e.g. `!google.com` in the additional list should override downloaded lists, but this does not happen and it is ignored completely. It is redundant. if `0.0.0.0 google.com` is included in the "downloaded blocklist", and whitelisted here, then it will still be blocked.

So the filter has no whitelisted mode at all.. There is no need to include any whitelisted entry because all unblocked entries are whitelisted by default..

**Comment by IngoZenz** [comment]
`!google.com` will only whitelist `google.com` and not the sub domains as `www.google.com`

**Comment by IngoZenz** [comment]
you can add your whitelisted domains in the beginning of the file and add "*" at the end in order to block everything else.
The logic is implemented in` private boolean contains(String hostName, long hosthash, boolean checkParent, boolean checkPattern)` line 367 within `master/app/src/main/java/dnsfilter/BlockedHosts.java`.
