### ISSUE TITLE
Remote connect failed on Android 9 device

### ISSUE THREAD

**Issue by QuadratClown** [IngoZenz/personaldnsfilter#46]
On my ZTE Blade V10 running Android 9 I get this error whenever I try to establish connection:

`Exception during initConnection(): java.net.ConnectException: failed to connect to /127.0.0.1 (port 3333) from /127.0.0.1 (port 57396) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
Remote Connect failed!java.net.ConnectException: failed to connect to /127.0.0.1 (port 3333) from /127.0.0.1 (port 57396) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)`

I'm not sure if that's a device, android-version or app related issue, which is why I posted it here.

**Comment by IngoZenz** [comment]
Seems the reason is that you did not configure the the IP Address of the host where the remote pDNSf instance is running.

Within dnsfilter.conf on Android you need to set:

 

client_remote_ctrl_host = <host ip where remote dns is running>

 

On the remote instance you need to enable the remote control via setting the port from -1 to e.g. 3333

 

server_remote_ctrl_port = 3333

**Comment by QuadratClown** [comment]
Thank you, fixed
