### ISSUE TITLE
"DNSFilter is running!" Notification cannot be removed

### ISSUE THREAD

**Issue by KlugB** [IngoZenz/personaldnsfilter#63]
With my last update to 1.50.36.0 DNSFilter creates a new notification "DNSFilter is running!" when running. Additionally the key symbol in the status bar is shown as previously. The notification is sticky and cannot be removed on my LG G4, Android 6.0.

I liked the previous behaviour. IMHO the key symbol is sufficient for information. Maybe it is possible to create an option to switch off this notification?

**Comment by KlugB** [comment]
Just found a **workaround**: Disable notifications for this app in Android settings. (Settings - Apps - DNSFilter - Uncheck "Show notifications")

Since I don't think I ever received notifications from DNSFilter this seems safe to me.

**Comment by kowith337** [comment]
Disable notification is no good due to battery optimization feature (aka. `DOZE`), that cause the app got killed and cannot run in background, it's very annoyance for some situation but please understand the system limitation in order to have this app fully functional.

In most versions of Android, you can set _Show silently and minimized_, the notifications will not show icons above but you will still see it when you reveal notification drop-down panel.

**Comment by IngoZenz** [comment]
Yes - since a certain android version it is a "must" to start services in foreground modus in case they should run without being killed. This mode requires the notification. 
So unfortunately there is nothing I can do here...

**Comment by KlugB** [comment]
Let me see if I understood this correctly. If I disable the notification, DOZE would kill the DNSFilter process at some time, and when I wake up my phone again DNSFilter would not start again by itself?

In other words, one kill by DOZE would make DNSFilter stop working in the background forever, unless I restart it manually?

**Comment by IngoZenz** [comment]
Nothing I can do here...
